package eventos;

public enum TipoEvento {
	INVALIDO, 
	CHEGADA, 
	REQUISICAO_MEMORIA,
	REQUISICAO_PROCESSADOR,
	PEDIDO_DISCO,
	REQUISICAO_DISCO,
	LIBERA_DISCO,
	PEDIDO_E_S,
	REQUISICAO_E_S,
	LIBERA_E_S,
	FALHA_DE_SEGMENTACAO,
	TERMINO;
}
